import Head from 'next/head'
import Image from 'next/image'
import { useContext } from 'react'
import Sidebar from '../components/Sidebar'
import Chat from '../components/Chat'
import { AuthContext } from '../context/AuthContext'

import styles from '../styles/Home.module.css'

export default function Home() {
  
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
      <Sidebar/>
      <Chat/>
      </div>
    </div>
  )
}


